//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Foundation

public class SuccessResponse: APIModel {

    public var message: String?

    public var statusScode: Int?

    public init(message: String? = nil, statusScode: Int? = nil) {
        self.message = message
        self.statusScode = statusScode
    }

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: StringCodingKey.self)

        message = try container.decodeIfPresent("message")
        statusScode = try container.decodeIfPresent("status_scode")
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: StringCodingKey.self)

        try container.encodeIfPresent(message, forKey: "message")
        try container.encodeIfPresent(statusScode, forKey: "status_scode")
    }

    public func isEqual(to object: Any?) -> Bool {
      guard let object = object as? SuccessResponse else { return false }
      guard self.message == object.message else { return false }
      guard self.statusScode == object.statusScode else { return false }
      return true
    }

    public static func == (lhs: SuccessResponse, rhs: SuccessResponse) -> Bool {
        return lhs.isEqual(to: rhs)
    }
}
