//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Foundation

/** Token model */
public class Token: APIModel {

    public var token: String?

    public init(token: String? = nil) {
        self.token = token
    }

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: StringCodingKey.self)

        token = try container.decodeIfPresent("token")
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: StringCodingKey.self)

        try container.encodeIfPresent(token, forKey: "token")
    }

    public func isEqual(to object: Any?) -> Bool {
      guard let object = object as? Token else { return false }
      guard self.token == object.token else { return false }
      return true
    }

    public static func == (lhs: Token, rhs: Token) -> Bool {
        return lhs.isEqual(to: rhs)
    }
}
